# Generated by Django 5.0.6 on 2024-07-05 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0003_alter_document_body_alter_document_context"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="context",
        ),
    ]
